### ISSUE TITLE
TimeoutError: [WinError 10060] A connection attempt failed

### ISSUE THREAD

**Issue by raymondclowe** [EdwardTheLegend/Google-analytics-and-search-console#27]
```
Traceback (most recent call last):
  File "\\dell\business\GitHub\Google-analytics-and-search-console\NewDownloads.py", line 92, in <module>
    results = service.searchanalytics().query(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 922, in execute
    resp, content = _retry_request(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 221, in _retry_request
    raise exception
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 190, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\oauth2client\transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\oauth2client\transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1985, in request
    (response, content) = self._request(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1589, in _conn_request
    response = conn.getresponse()
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by raymondlowe** [comment]
Another timeout example, but on a different line:


Traceback (most recent call last):
  File "\\dell\business\GitHub\Google-analytics-and-search-console\GACombined2.py", line 107, in <module>
    profiles = service.management().profiles().list(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 922, in execute
    resp, content = _retry_request(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 221, in _retry_request
    raise exception
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 190, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\oauth2client\transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\oauth2client\transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1985, in request
    (response, content) = self._request(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1557, in _conn_request
    conn.connect()
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1391, in connect
    raise socket_err
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\site-packages\httplib2\__init__.py", line 1326, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\raymo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
←[?25h
